# Numpy Learning Notebook by NamKodX

## 1-Numpy nedir:

In [1]:
!pip install numpy 

Komutu sayesinde numpy kütüphanesini bilgisayarınıza yükleyebilirsiniz

In [5]:
python_list = [1,2,3,4,5,6,7,8,9]
#Basit python listesi

In [6]:
print(type(python_list))

<class 'list'>


Numpy gelişmiş liste,dizi yapısı gibi düşünebiliriz

In [4]:
import numpy as np
#Numpy kütüphanesini np olarak içeri aktarmamıza yarar

In [8]:
numpy_arrray = np.array([1,2,3,4,5,6,7,8,9])

Numpy array içine bir liste yazarak bir numpyarray (numpy dizisi yarattık)

In [10]:
print(numpy_arrray)
print(type(numpy_arrray))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
numpy_multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
#numpy_multi_array = np.array([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])

Yapısı sayesinde multi array yani çoklu dizi matris biçimi oluşturduk

In [13]:
print(numpy_multi_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
numpy_multi = numpy_arrray.reshape(3,3)

.reshape(satır,sütun) yapısı sayesinde boyutunu ayarladık

In [17]:
print(numpy_multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(numpy_arrray.ndim)
print(numpy_multi.ndim)

1
2


.ndim sayesinde boyut kontrolü yaptık 

Vektörler -> 1 | Boyut Matrisler -> 2 Boyut | Tensorflow(Çok Boyutlu Matris) -> 3 Boyutlu

In [22]:
print(numpy_arrray.shape)
print(numpy_multi.shape)

(9,)
(3, 3)


.shape ile kaça kaçlık ifade olduğunu anlarız.Kaç satır ve kaç sütun olduğuna bakmış oluyoruz

## 2- Numpy dizileri ile çalışma:

In [26]:
result = np.arange(1,100,3)
#np.arange(başlangıç,bitiş,artış)

In [27]:
print(result)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


.arange 1 den 100 e kadar 3 er 3 er artan dizi yaratmamızı sağlar 

In [28]:
result = np.zeros(10)

In [29]:
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


.zeros ile sıfır dizisi yada matrisi oluşturabiliriz

In [31]:
result = np.ones(10)

In [32]:
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


.ones ile bir dizisi yada matrisi oluşturabiliriz

In [38]:
result = np.linspace(0,100,5)
#np.linspace(başlangıç,bitiş,aynımesafedeolacaksayısayısı)

.linspace yapısı ile bir sayıdan bir sayıya istediğimiz kadar aynı mesafede sayı üretebiliriz

In [36]:
print(result)

[  0.  25.  50.  75. 100.]


In [51]:
result = np.random.randint(0,10,3)
print(result)
#np.random.randint(başlangıç,bitiş,adet)

[5 9 6]


.random.randint ile beraber random integer sayı üretebiliriz

In [54]:
result = np.random.rand(5)
print(result)

[0.18107492 0.66305004 0.68361127 0.5977614  0.38540938]


np.random.rand yapısı ile istediğimiz kadar 0 ile 1 arasında sayı üretebiliriz

In [55]:
result = np.random.randn(5)
print(result)

[ 0.08312818 -0.44237108  0.3010344   0.99604731 -0.21785011]


np.random.randn ile yukarıdaki işlem gibi lakin eksi sayılarda araya katılır

In [58]:
numpy_array = np.arange(50)
result = numpy_array.reshape(5,10)
print(result)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [59]:
print(result.sum(axis=1))
#Satırların toplamını getirir

[ 45 145 245 345 445]


In [61]:
print(result.sum(axis=0))
#Sütunların toplamını verir

[100 105 110 115 120 125 130 135 140 145]


In [62]:
random_numbers = np.random.randint(1,100,10)
print(random_numbers)

[20 33 54 76 69 30 88 92 66 49]


In [65]:
result = random_numbers.max()
print(result)
#Dizinin maximum değerini bulur

92


In [64]:
result = random_numbers.min()
print(result)
#Dizinin minimum değerini bulur

20


In [66]:
result = random_numbers.mean()
print(result)
#Dizinin ortalama değerini bulur

57.7


In [68]:
result = random_numbers.argmax()
print(result)
#Dizinin en büyük sayısının index numarasını bulur

7


In [70]:
result = random_numbers.argmin()
print(result)
#Dizinin en küçük sayısının index numarasını bulur

0


## 3- Numpy dizilerinin indexlenmesi:

In [73]:
numbers = np.array([0,5,10,15,20,25,50,75])

In [75]:
result = numbers[5]
print(result)

25


Köşeli parantez sayesinde listelerdeki gibi index numarasındaki elemanı alabiliriz işlem yapabiliriz onunla

In [77]:
result = numbers[-1]
print(result)
#-1 ile son index elemanını alabiliriz

75


In [79]:
result = numbers[0:3]
print(result)
#İstediğimiz index elemanlarını alabiliriz

[ 0  5 10]


In [82]:
result = numbers[::]
print(result)
#İstediğimiz tüm index elemanlarını alabiliriz

[ 0  5 10 15 20 25 50 75]


In [84]:
result = numbers[::-1]
print(result)
#İstediğimiz tüm index elemanlarını tersten alabiliriz

[75 50 25 20 15 10  5  0]


In [87]:
numpy_multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(numpy_multi_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
result = numpy_multi_array[0][2]
print(result)
#Satır ve sütün seçimi için iki tane köşeli parantez kullanılmalıdır

3


In [91]:
result = numpy_multi_array[0,2]
print(result)
#Satır ve sütün seçimi için yada tek köşeli parantez iki değer kullanılmalıdır

3


In [94]:
result = numpy_multi_array[:,2]
print(result)
#Tüm satırlar ve 2. indexli sütunları almak için kullanılır

[3 6 9]


## 4-Numpy Dizi Operasyonları:

In [95]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

In [97]:
print(numbers1)
print(numbers2)

[67 67 50 99 63 88]
[15 25 63 98 43 79]


In [99]:
result = numbers1 + numbers2
print(result)
#Aynı indexteki elemanlar toplanmış olur

[ 82  92 113 197 106 167]


In [100]:
result = numbers1 - numbers2
print(result)
#Aynı indexteki elemanlar çıkarılmış olur

[ 52  42 -13   1  20   9]


In [101]:
result = numbers1 * numbers2
print(result)
#Aynı indexteki elemanlar çarpılmış olur

[1005 1675 3150 9702 2709 6952]


In [102]:
result = numbers1 / numbers2
print(result)
#Aynı indexteki elemanlar çarpılmış olur

[4.46666667 2.68       0.79365079 1.01020408 1.46511628 1.11392405]


In [105]:
result = np.sin(numbers1)
print(result)
#Dizinin sinüsünü alabiliriz

[-0.85551998 -0.85551998 -0.26237485 -0.99920683  0.1673557   0.0353983 ]


In [106]:
result = np.cos(numbers1)
print(result)
#Dizinin cosinüsünü alabiliriz

[-0.5177698  -0.5177698   0.96496603  0.03982088  0.98589658  0.99937328]


In [108]:
result = np.sqrt(numbers1)
print(result)
#Dizinin kökünü alabiliriz

[8.18535277 8.18535277 7.07106781 9.94987437 7.93725393 9.38083152]


In [109]:
result = np.log(numbers1)
print(result)
#Dizinin ln nini alabiliriz

[4.20469262 4.20469262 3.91202301 4.59511985 4.14313473 4.47733681]


In [112]:
mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

In [114]:
print(mnumbers1)
print(mnumbers2)

[[67 67 50]
 [99 63 88]]
[[15 25 63]
 [98 43 79]]


In [119]:
result = np.vstack((mnumbers1,mnumbers2))
print(result)
#Dikey olarak matrisleri birleştirir

[[67 67 50]
 [99 63 88]
 [15 25 63]
 [98 43 79]]


In [122]:
result = np.hstack((mnumbers1,mnumbers2))
print(result)
#Yatay olarak matrisleri birleştirir

[[67 67 50 15 25 63]
 [99 63 88 98 43 79]]


In [126]:
result = numbers1 >= 69
print(result)
#Kontrol işlemi for yapmadan daha kolay yapılmış oldu

[False False False  True False  True]


In [132]:
result = numbers2 %2 == 1
print(result)
#Tekleri ve çiftlerin kontrolünü for döngüsü kullanmadan yapmış olduk

[ True  True  True False  True  True]


In [133]:
result = numbers2[result]
print(result)

[15 25 63 43 79]


Tekleri ve çiftlerin kontrolünü yaptığımız sayıları boolen tipinde değil değerinde almak için köşeli parantez yerine kontrol yaptıklarımızı yazarız